"""add telegam_id, rm phone

Revision ID: 7b56684284c5
Revises: f7037cf9fc69
Create Date: 2021-02-11 10:15:33.699381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b56684284c5'
down_revision = 'f7037cf9fc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.alter_column('telegram_user', 'last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.drop_column('telegram_user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('telegram_user', 'last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('telegram_user', 'telegram_id')
    # ### end Alembic commands ###
