"""add tables

Revision ID: f7037cf9fc69
Revises: 
Create Date: 2021-02-03 11:29:33.022657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7037cf9fc69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('not_specified', 'technical_worker', 'sanitary_worker', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('attachment', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_process', 'closed', name='status'), nullable=False),
    sa.Column('worker', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['telegram_user.id'], ),
    sa.ForeignKeyConstraint(['worker'], ['telegram_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_open_date'), 'defect', ['open_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defect_open_date'), table_name='defect')
    op.drop_table('defect')
    op.drop_table('telegram_user')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
